# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-24 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20190620_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content_html',
            field=models.TextField(blank=True, editable=False, verbose_name='正文html代码'),
        ),
    ]
